function xi = menentukannilaixi(TD)
    D = 100 * 10^6;
    theta = 0.2;
    ch = 0.002;
    delta = 850;
    TD = 0.0723;

    f = @(xi) -(D * ( ...
        2 * ch * delta - exp((TD * theta)) / (delta * xi + 1) + ...
        TD * theta + ...
        4 * delta * xi + ...
        3 * delta^2 * xi^2 - ...
        3 * delta^2 * xi^2 * exp((TD * theta) / (delta * xi + 1)) - ...
        2 * ch * delta * exp((TD * theta) / (delta * xi + 1)) - ...
        4 * delta * xi * exp((TD * theta) / (delta * xi + 1)) + ...
        2 * ch * delta^2 * xi + ...
        2 * TD * delta * theta * xi - ...
        2 * ch * delta^2 * xi * exp((TD * theta) / (delta * xi + 1)) + ...
        TD * ch * delta * theta + ...
        TD * ch * delta * theta * exp((TD * theta) / (delta * xi + 1)) + ...
        TD * delta * theta * xi * exp((TD * theta) / (delta * xi + 1)) + 1)) / (TD * theta^2);

    options = optimset('Display', 'iter', 'TolFun', 1e-10, 'TolX', 1e-10);

    xi0 = exp(-5 * TD);
    
    xi = fsolve(f, xi0, options);

    fprintf('Optimized xi = %.7f for TD = %.4f xi0 = %.4f \n', xi, TD, xi0);
end
